urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView

from oscar.views import handler500, handler404

from app import application

admin.autodiscover()

urlpatterns = patterns('',
                       (r'^admin/', include(admin.site.urls)),
                       (r'', include(application.urls)),
                       )

urlpatterns += patterns('',
                        url(r'^dich-anh-viet/', include('rosetta.urls')),
                        url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                        url(r'^oauth/', include('social_django.urls', namespace='social')),
                        url(r'^oauth/', include('django.contrib.auth.urls', namespace='auth')),
                        url(r'^favicon.ico/$', RedirectView.as_view(
                            url='/static/binhphuoc/favicon.ico', permanent=True)
                            ),
                        url(r'^lien-he/', include('contact_form.urls')),
                        )
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += patterns('',
                            url(r'^404$', handler404),
                            url(r'^500$', handler500),
                            )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/document/models.py
# -*- coding: utf-8 -*-
from datetime import date

from django.core.urlresolvers import reverse
from django.db import models
from django.core.cache import cache
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from oscar.core.utils import slugify

from .settings import LEGAL_DOCUMENT_FILE_FOLDER


class LegalDocument(models.Model):
    """
    Model cho Văn bản quy phạm pháp luật
    Các thông tin lấy từ
    http://vbpl.vn/Pages/portal.aspx
    """
    EFF, EXP = ('Eff', 'Exp')
    STATUS_CHOICES = (
        (EFF, _(u"Còn hiệu lực")),
        (EXP, _(u"Hết hiệu lực")),
    )

    CONS, CODE, LAW, ORDI, ORDE, RESO, JRES, DECR, DECI, CIRC, JCIR = (
        'Constitution', 'Code', 'Law', 'Ordinance', 'Order', 'Resolution',
        'Joint Resolution', 'Decree', 'Decision', 'Circular', 'Joint circular')

    LEGISLATION_CHOICES = (
        (CONS, _(u"Hiến pháp")),
        (CODE, _(u"Bộ luật")),
        (LAW, _(u"Luật")),
        (ORDI, _(u"Pháp lệnh")),
        (ORDE, _(u"Lệnh")),
        (RESO, _(u"Nghị quyết")),
        (JRES, _(u"Nghị quyết liên tịch")),
        (DECR, _(u"Nghị định")),
        (DECI, _(u"Quyết định")),
        (CIRC, _(u"Thông tư")),
        (JCIR, _(u"Thông tư liên tịch")),
    )
    # http://vbpl.vn/TW/Pages/cacboen.aspx
    # http://vbpl.vn/TW/Pages/cacbo.aspx
    ISSUING_BODY_CHOICES = (
        ('State President', _(u"Chủ tịch nước")),
        ('The Government', _(u"Chính phủ")),
        ('Prime Minister', _(u"Thủ tướng Chính phủ")),
        ('Ministry of Industry and Trade', _(u"Bộ Công Thương")),
        ('Ministry of Planning and Investment', _(u"Bộ Kế hoạch và Đầu tư")),
        ('The Ministry of Science and Technology', _(u"Bộ Khoa học và Công nghệ")),
    )

    OFFICIAL_NUMBER_PATTERN = '__/____/____-____'
    title = models.CharField(_(u'Tiêu đề'),
                             max_length=255, blank=True)
    official_number = models.CharField(_(u"Số ký hiệu"), max_length=128,
                                       default=OFFICIAL_NUMBER_PATTERN, unique=True, blank=False)
    status = models.CharField(_(u"Hiệu lực văn bản"),
                              max_length=3, choices=STATUS_CHOICES, blank=True)
    slug = models.SlugField(_('Slug'), max_length=255, unique=False)
    description = models.TextField(_('Description'), blank=True)
    content = models.TextField(_('Content'), blank=True)

    date_created = models.DateTimeField(_("Date created"), auto_now_add=True)
    date_updated = models.DateTimeField(
        _("Date updated"), auto_now=True, db_index=True)
    published_date = models.DateField(_(u"Ngày ban hành"), blank=True, null=True)
    validated_date = models.DateField(_(u"Ngày hiệu lực"), blank=True, null=True)

    legislation_type = models.CharField(_(u"Loại văn bản"),
                                        max_length=128, choices=LEGISLATION_CHOICES, blank=True)
    issuing_body = models.CharField(_(u"Đơn vị ban hành"),
                                    max_length=128, choices=ISSUING_BODY_CHOICES, blank=True)

    signer_name = models.CharField(_(u'Người ký'),
                                   max_length=255, blank=True)
    signer_position = models.CharField(_(u'Chức vụ'),
                                       max_length=255, blank=True)

    file = models.FileField(_(u'Tệp đính kèm'), upload_to=LEGAL_DOCUMENT_FILE_FOLDER, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(LegalDocument, self).save(*args, **kwargs)

    @staticmethod
    def get_latest_by_issue(issuing_body=None, num=20):
        """
        """
        if issuing_body:
            return LegalDocument.objects.filter(issuing_body=issuing_body).order_by('-published_created')[:num]
        else:
            return LegalDocument.objects.all().order_by('-published_created')[:num]

    @staticmethod
    def get_latest_by_type(legislation_type=None, num=20):
        """
        """
        if legislation_type:
            return LegalDocument.objects.filter(legislation_type=legislation_type).order_by('-published_created')[:num]
        else:
            return LegalDocument.objects.all().order_by('-published_created')[:num]

    def get_absolute_url(self):
        """
        Return a document's absolute url
        """
        cache_key = 'LEGAL_DOCUMENT_URL_%s' % self.pk
        url = cache.get(cache_key)
        if not url:
            url = reverse(
                'document:detail',
                kwargs={'legal_document_slug': self.slug, 'pk': self.pk})
            cache.set(cache_key, url)
        return url

    def __unicode__(self):
        return self.title

    def is_expired(self):
        if not self.validated_date:
            return True
        if date.today() >= self.validated_date:
            return False
        return True

    def get_other_documents(self, num=5):
        """
        :param num:
        :return:
        """
        return LegalDocument.objects.filter(~Q(id=self.id)).order_by('-date_updated')[:num]

    class Meta:
        app_label = 'document'
        ordering = ['-published_date']
        verbose_name = _('LegalDocument')
        verbose_name_plural = _('LegalDocument')

apps/dashboard/document/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from oscar.core.loading import get_model


LegalDocument = get_model('document', 'LegalDocument')


class LegalDocumentForm(forms.ModelForm):
    class Meta:
        model = LegalDocument
        fields = ['title', 'official_number', 'description', 'content', 'published_date', 'validated_date',
                  'legislation_type', 'issuing_body', 'signer_name', 'signer_position', 'file']


class LegalDocumentSearchForm(forms.Form):
    title = forms.CharField(max_length=255, required=False, label=_('Title'))

apps/dashboard/document/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils.translation import ugettext_lazy as _

from django_tables2 import SingleTableMixin
from oscar.core.loading import get_model, get_class
from oscar.views.generic import ObjectLookupView


LegalDocument = get_model('document', 'LegalDocument')
LegalDocumentTable = get_class('dashboard.document.tables', 'LegalDocumentTable')
LegalDocumentForm = get_class('dashboard.document.forms', 'LegalDocumentForm')
LegalDocumentSearchForm = get_class('dashboard.document.forms', 'LegalDocumentSearchForm')


class LegalDocumentListView(SingleTableMixin, generic.TemplateView):
    template_name = 'dashboard/document/document_item_list.html'
    table_class = LegalDocumentTable
    form_class = LegalDocumentSearchForm
    context_table_name = 'document_items'

    def get_context_data(self, **kwargs):
            ctx = super(LegalDocumentListView, self).get_context_data(**kwargs)
            ctx['form'] = self.form
            return ctx

    def get_queryset(self):
        queryset = LegalDocument.objects.all().order_by('-date_updated')
        queryset = self.apply_search(queryset)
        return queryset

    def apply_search(self, queryset):
            """
            Filter the queryset and set the description according to the search
            parameters given
            """
            self.form = self.form_class(self.request.GET)

            if not self.form.is_valid():
                return queryset

            data = self.form.cleaned_data

            if data.get('title'):
                queryset = queryset.filter(title__icontains=data['title'])
            return queryset


class LegalDocumentListMixin(object):

    def get_success_url(self):
        return reverse("dashboard:document-item-list")


class LegalDocumentCreateView(LegalDocumentListMixin, generic.CreateView):
    template_name = 'dashboard/document/document_item_form.html'
    model = LegalDocument
    form_class = LegalDocumentForm

    def get_context_data(self, **kwargs):
        ctx = super(LegalDocumentCreateView, self).get_context_data(**kwargs)
        ctx['title'] = _("Add a document item")
        return ctx

    def get_success_url(self):
        messages.info(self.request, _("LegalDocument created successfully"))
        return super(LegalDocumentCreateView, self).get_success_url()


class LegalDocumentUpdateView(LegalDocumentListMixin, generic.UpdateView):
    template_name = 'dashboard/document/document_item_form.html'
    model = LegalDocument
    form_class = LegalDocumentForm

    def get_context_data(self, **kwargs):
        ctx = super(LegalDocumentUpdateView, self).get_context_data(**kwargs)
        ctx['title'] = _("Update item '%s'") % self.object.title
        return ctx

    def get_success_url(self):
        messages.info(self.request, _("LegalDocument updated successfully"))
        return super(LegalDocumentUpdateView, self).get_success_url()


class LegalDocumentDeleteView(LegalDocumentListMixin, generic.DeleteView):
    template_name = 'dashboard/document/document_item_delete.html'
    model = LegalDocument

    def get_context_data(self, *args, **kwargs):
        ctx = super(LegalDocumentDeleteView, self).get_context_data(*args, **kwargs)
        return ctx

    def get_success_url(self):
        messages.info(self.request, _("LegalDocument Category deleted successfully"))
        return super(LegalDocumentDeleteView, self).get_success_url()


class LegalDocumentLookupView(ObjectLookupView):
    model = LegalDocument

    def get_queryset(self):
        return self.model.ojbects.all()

    def lookup_filter(self, qs, term):
        return qs.filter(title__icontains=term)

apps/document/views.py
# -*- coding:utf-8 -*-

from django.conf import settings
from django.views.generic import ListView, DetailView

from oscar.core.loading import get_model

if settings.THEMES:
    THEME = settings.THEMES[0]

LegalDocument = get_model('document', 'LegalDocument')
Partner = get_model('partner', 'Partner')
Banner = get_model('promotions', 'Banner')


class DocumentView(ListView):
    model = LegalDocument
    ordering = '-published_date'
    paginate_by = 20

    template_name = '%s/document/all-legal-document.html' % THEME
    num_enterprises = 20

    @staticmethod
    def get_banner_list(group_order, banner_in_type, display_in_page):
        banner_list = Banner.objects.filter(group_order=group_order, banner_in_type=banner_in_type, active=True,
                                            page=display_in_page).order_by('local_order')
        return banner_list

    def get_context_data(self, **kwargs):
        ctx = super(DocumentView, self).get_context_data(**kwargs)
        ctx['enterprises'] = Partner.objects.all().order_by('?')[:self.num_enterprises]
        ctx['news_banners'] = self.get_banner_list(group_order=0, banner_in_type='IBP', display_in_page='NEWS')
        return ctx


class DocumentDetailView(DetailView):
    model = LegalDocument
    context_object_name = 'document'
    template_name = '%s/document/legal-document-detail.html' % THEME
    num_enterprises = 20

    def get_context_data(self, **kwargs):
        ctx = super(DocumentDetailView, self).get_context_data(**kwargs)
        ctx['other_documents'] = self.get_object().get_other_documents()
        ctx['enterprises'] = Partner.objects.all().order_by('?')[:self.num_enterprises]
        return ctx

templates/binhphuoc/document/all-legal-document.html
{% extends "binhphuoc/layout.html" %}
{% load i18n %}
{% load static %}
{% load thumbnail %}
{% load v_display_tags %}
{% block layout %}
    <header>
        {# Top-horizontal bar with account, notifictions, dashboard links #}
        {% include "binhphuoc/partials/top_header.html" %}
        {% include "binhphuoc/partials/nav_primary.html" %}
    </header>
    {# Main content of page - other layout templates may override this block #}
    <div class="breadcrumb-area mb-20">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="breadcrumb-container">
                        <ul>
                            <li>
                                <a href="{{ homepage_url }}"><i class="fa fa-home mr-1"></i>{% trans "Home" %}</a>
                            </li>
                            <li class="active">
                                <a href="{% url 'document:index' %}">{% trans "Văn bản pháp luật" %}</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blog-page-container mb-50">
        <div class="container">
            <div class="row">
                {% if object_list %}
                    <div class="col">
                        <div class="blog-post-container">
                            {% for n in object_list %}
                                <div class="single-blog-post mb-35">
                                    <div class="single-blog-post-content">
                                        <h3 class="post-title"><a href="{{ n.get_absolute_url }}"><i
                                                class="fa fa-file-text"
                                                style="color:red;"></i>
                                            <span class="date"> {{ n.get_legislation_type_display }} {{ n.official_number }}</span></a>
                                        </h3>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-9">
                                            <p class="post-excerpt">{{ n.title }}</p>
                                        </div>
                                        <div class="col-md-3">
                                            <p class="post-excerpt m-0">
                                                <label style="font-weight: bold"> {% trans "Ban hành:" %}</label><span
                                                    style="float: right;"><i
                                                    class="one-space"></i>{{ n.published_date|date:"SHORT_DATE_FORMAT" }}</span>
                                            </p>
                                            <p class="post-excerpt m-0">
                                                <label style="font-weight: bold"> {% trans "Hiệu lực:" %}</label><span
                                                    style="float: right;"><i
                                                    class="one-space"></i>{{ n.validated_date|date:"SHORT_DATE_FORMAT" }}</span>
                                            </p>
                                            {% if n.is_expired %}
                                                <p class="post-excerpt m-0">
                                                    <label> {% trans "Trạng thái:" %}</label><span
                                                        style="float: right;"> {% trans "Chưa có hiệu lực" %}</span>
                                                </p>
                                            {% endif %}
                                        </div>
                                    </div>
                                    {% if n.file %}
                                        <div class="single-blog-post-content">
                                            <i class="fa fa-download" style="color: green"></i>
                                            <a href="{{ n.file.url }}">
                                                {% trans "Tải về" %}
                                            </a>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                        {% paginator 2 "binhphuoc/partials/pagination.html" %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    {# footer #}
    {% include "binhphuoc/partials/footer.html" %}
{% endblock %}

templates/binhphuoc/document/legal-document-detail.html
{% extends "binhphuoc/layout_2_col.html" %}
{% load i18n %}
{% load static %}
{% load thumbnail %}
{% block layout %}
    <header>
        {# Top-horizontal bar with account, notifictions, dashboard links #}
        {% include "binhphuoc/partials/top_header.html" %}
        {% include "binhphuoc/partials/nav_primary.html" %}
    </header>
    {# Main content of page - other layout templates may override this block #}
    <div class="breadcrumb-area mb-20">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="breadcrumb-container">
                        <ul>
                            <li>
                                <a href="{{ homepage_url }}"><i class="fa fa-home mr-1"></i>{% trans "Home" %}</a>
                            </li>
                            <li>
                                <a href="{% url 'document:index' %}">{% trans "Văn bản pháp luật" %}</a>
                            </li>
                            <li class="active">
                                <a href="{{ document.get_absolute_url }}">{{ document.get_legislation_type_display }} {{ document.official_number }}</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blog-page-container mb-50">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="blog-post-container">
                        <div class="single-blog-post mb-35">
                            <div class="single-blog-post-content">
                                <h3 class="post-title"><i class="fa fa-file-text" style="color:red;"></i>
                                    <span class="date"> {{ document.get_legislation_type_display }} {{ document.official_number }}</span>
                                    <span>: {{ document.title }}</span>
                                </h3>
                                <hr/>
                                <div class="row">
                                    <div class="col-md-4">
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Trạng thái:" %}</label>
                                            {% if document.is_expired %}
                                                <span style="float: right;">{% trans "Chưa có hiệu lực" %}</span>
                                            {% else %}
                                                <span style="float: right;">{% trans "Còn hiệu lực" %}</span>
                                            {% endif %}
                                        </p>
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Số ký hiệu:" %}</label><span
                                                style="float: right;"><i
                                                class="one-space"></i>{{ document.official_number }}</span>
                                        </p>
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Tên văn bản :" %}</label><span
                                                style="float: right;"><i
                                                class="one-space"></i>{{ document.title|truncatewords:6 }}</span>
                                        </p>
                                    </div>
                                    <div class="col-md-4">
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Ngày ban hành:" %}</label><span
                                                style="float: right;"><i
                                                class="one-space"></i>{{ document.published_date|date:"SHORT_DATE_FORMAT" }}</span>
                                        </p>
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Ngày hiệu lực:" %}</label><span
                                                style="float: right;"><i
                                                class="one-space"></i>{{ document.validated_date|date:"SHORT_DATE_FORMAT" }}</span>
                                        </p>
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Loại văn bản:" %}</label><span
                                                style="float: right;"><i
                                                class="one-space"></i>{{ document.get_legislation_type_display }}</span>
                                        </p>
                                    </div>
                                    <div class="col-md-4">
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Đơn vị ban hành:" %}</label><span
                                                style="float: right;"><i
                                                class="one-space"></i>{{ document.get_issuing_body_display }}</span>
                                        </p>
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Người ký:" %}</label><span
                                                style="float: right;"><i
                                                class="one-space"></i>{{ document.signer_name }}</span>
                                        </p>
                                        <p class="post-excerpt m-0">
                                            <label style="font-weight: bold"> {% trans "Chức vụ:" %}</label><span
                                                style="float: right;"><i
                                                class="one-space"></i>{{ document.signer_position }}</span>
                                        </p>
                                    </div>
                                </div>
                                <br/>
                                {% if document.file %}
                                    <div class="single-blog-post-content">
                                        <i class="fa fa-download" style="color: green"></i>
                                        <a href="{{ document.file.url }}">
                                            {% trans "Tải về" %}
                                        </a>
                                    </div>
                                {% endif %}
                                {% if document.description %}
                                    <p class="post-excerpt">
                                        {{ document.description|safe }}
                                    </div>
                                {% endif %}
                            {% if document.content %}
                                <hr/>
                                <p class="post-excerpt">
                                    {{ document.content|safe }}
                                </p>
                                {% if document.file %}
                                    <div class="single-blog-post-content">
                                        <i class="fa fa-download" style="color: green"></i>
                                        <a href="{{ document.file.url }}">
                                            {% trans "Tải về" %}
                                        </a>
                                    </div>
                                {% endif %}
                            {% endif %}
                        </div>
                        {% if other_documents %}
                            <hr>
                            <div class="single-blog-post-content">
                                <h3 class="post-title">{% trans "Các văn bản khác" %}</h3>
                                <ul>
                                    {% for odocument in other_documents %}
                                        <li><i class="fa fa-check"></i>&nbsp;<a
                                                href="{{ odocument.get_absolute_url }}">{{ odocument.title }}<span> ({{ document.date_updated|date:"SHORT_DATE_FORMAT" }})</span></a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="pagination pull-right">
                                <a href="{% url 'document:index' %}">{% trans 'Xem thêm' %}
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {# footer #}
    {% include "binhphuoc/partials/footer.html" %}
{% endblock %}